# Generated by Django 5.2.11 on 2026-02-19 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('child_name', models.CharField(blank=True, max_length=200, null=True)),
                ('child_age', models.IntegerField(blank=True, null=True)),
                ('sport', models.CharField(blank=True, max_length=100, null=True)),
                ('academy_name', models.CharField(blank=True, max_length=200, null=True)),
                ('campaign_goal', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=50)),
                ('preferred_channel', models.CharField(blank=True, max_length=20, null=True)),
                ('total_interactions', models.IntegerField(default=0)),
                ('total_voice_attempts', models.IntegerField(default=0)),
                ('total_sms_attempts', models.IntegerField(default=0)),
                ('total_email_attempts', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('extracted_facts', models.JSONField(blank=True, default=list)),
                ('detected_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=30, null=True)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('provider_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.lead')),
            ],
            options={
                'db_table': 'interactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=36, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.lead')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_artifacts', to='app.interaction')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_artifacts', to='app.lead')),
            ],
            options={
                'db_table': 'context_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NBADecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('channel', models.CharField(blank=True, max_length=20, null=True)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('reasoning', models.TextField()),
                ('policy_inputs', models.JSONField(blank=True, default=dict)),
                ('rule_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nba_decisions', to='app.interaction')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nba_decisions', to='app.lead')),
            ],
            options={
                'db_table': 'nba_decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_actions', to='app.lead')),
                ('nba_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_actions', to='app.nbadecision')),
            ],
            options={
                'db_table': 'scheduled_actions',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['lead', '-created_at'], name='idx_interaction_lead_date'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['lead', '-created_at'], name='idx_event_lead_date'),
        ),
        migrations.AddIndex(
            model_name='contextartifact',
            index=models.Index(fields=['lead', 'artifact_type', 'is_current'], name='idx_artifact_lead_type_cur'),
        ),
        migrations.AddIndex(
            model_name='contextartifact',
            index=models.Index(fields=['lead', 'is_current'], name='idx_artifact_lead_current'),
        ),
        migrations.AddIndex(
            model_name='nbadecision',
            index=models.Index(fields=['lead', 'is_current'], name='idx_nba_lead_current'),
        ),
        migrations.AddIndex(
            model_name='scheduledaction',
            index=models.Index(fields=['status', 'scheduled_at'], name='idx_action_status_sched'),
        ),
    ]
