# Generated by Django 5.2.11 on 2026-02-19 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbadecision',
            name='action_brief',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nbadecision',
            name='rl_q_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbadecision',
            name='rl_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nbadecision',
            name='signal_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='QValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('q_value', models.FloatField(default=0.0)),
                ('visit_count', models.IntegerField(default=0)),
                ('total_reward', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'q_values',
                'indexes': [models.Index(fields=['state'], name='idx_qvalue_state')],
                'unique_together': {('state', 'action')},
            },
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_before', models.CharField(max_length=100)),
                ('action_taken', models.CharField(max_length=50)),
                ('state_after', models.CharField(max_length=100)),
                ('reward', models.FloatField()),
                ('q_value_before', models.FloatField()),
                ('q_value_after', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='app.lead')),
                ('nba_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_transitions', to='app.nbadecision')),
            ],
            options={
                'db_table': 'state_transitions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='idx_transition_lead_date')],
            },
        ),
    ]
