# Generated by Django 5.2.11 on 2026-02-19 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nbadecision_action_brief_nbadecision_rl_q_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSBuffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('sender', models.CharField(blank=True, default='', max_length=100)),
                ('received_at', models.DateTimeField(help_text='Real-world timestamp of the SMS')),
                ('is_urgent', models.BooleanField(default=False)),
                ('flushed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flushed_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_sms_messages', to='app.interaction')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_buffer', to='app.lead')),
            ],
            options={
                'db_table': 'sms_buffer',
                'ordering': ['received_at'],
                'indexes': [models.Index(fields=['lead', 'flushed', 'received_at'], name='idx_smsbuffer_lead_pending')],
            },
        ),
    ]
