# Generated by Django 5.2.11 on 2026-02-19 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lead_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsbuffer',
            name='flushed_interaction',
        ),
        migrations.AddField(
            model_name='smsbuffer',
            name='interaction',
            field=models.OneToOneField(blank=True, help_text='The individual Interaction created for this message (for display)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_buffer_entry', to='app.interaction'),
        ),
    ]
