# Generated by Django 5.2.11 on 2026-02-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sms_buffer_individual_interactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
